## Getting Started with Numpy

** Memory consumption: ndarray and list **
The main benefits of using numpy are its smaller memory consumption and better runtime behavior


In [1]:
from sys import getsizeof as size
lst = [24, 12, 57]
size_of_list_object = size(lst)
size_of_elements = len(lst) * size(lst[0]) 
total_list_size = size_of_list_object + size_of_elements
print("Size without the size of the elements: ", size_of_list_object)
print("Size of all the elements: ", size_of_elements)
print("Total size of list, including elements: ", total_list_size)

#The size of the python list will only return the size of the list. It is the size need for the reference to the elements and the size of all elements of the list. 
# Larger integers will tend to consume more memory

Size without the size of the elements:  88
Size of all the elements:  84
Total size of list, including elements:  172


In [2]:
#Check what happens when we add another integer
lst = [24, 12, 57, 42]
size_of_list_object = size(lst)
size_of_elements = len(lst) * size(lst[0]) 
total_list_size = size_of_list_object + size_of_elements
print("Size without the size of the elements: ", size_of_list_object)
print("Size of all the elements: ", size_of_elements)
print("Total size of list, including elements: ", total_list_size)

lst=[]
print("Empty list size: ", size(lst))

## From this we can conclude that for every new element we need another 8 bytes of for the reference to the new object


Size without the size of the elements:  96
Size of all the elements:  112
Total size of list, including elements:  208
Empty list size:  64


In [3]:
## Check the numpy array
import numpy as np
a = np.array([24, 12, 57])
print(size(a))

e = np.array([])
print(size(e))

120
96


In [4]:
a = np.array([24, 12, 57], np.int8)
print(size(a) - 96)
a = np.array([24, 12, 57], np.int16)
print(size(a) - 96)
a = np.array([24, 12, 57], np.int32)
print(size(a) - 96)
a = np.array([24, 12, 57], np.int64)
print(size(a) - 96)


3
6
12
24


In [8]:
import time
size_of_vec = 90000000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numy is in this example " + str(t1/t2) + " faster!")
    

29.492273092269897 1.2104828357696533
Numy is in this example 24.364057234663736 faster!


### Slicing 

* `s[i]` (indexing)
* `s[i:j]` (slicing)
* `s[i:j:k]` (step slicing)
* meaning of negative indices
* 0-base counting

The triple [i:j:k] are in fact parameters of a **slice** object:

### slice(start, stop[, step])
> Return a slice object representing the set of indices specified by range(start, stop, step). The start and step arguments default to None. Slice objects have read-only data attributes start, stop and step which merely return the argument values (or their default). They have no other explicit functionality; however they are used by Numerical Python and other third party extensions. Slice objects are also generated when extended indexing syntax is used. For example: a[start:stop:step] or a[start:stop, i].

http://docs.python.org/2/library/functions.html#slice

For example, to return the first 3 elements in the even positions of a list, you can use:

In [11]:
m = list(range(10))
m[slice(0,5,2)]

[0, 2, 4]

In [13]:
m[0:5:2]

[0, 2, 4]

### Shaping and Array Creation


In [15]:
# zero-dimensions
a0 = np.array(5)
a0

array(5)

In [16]:
a0.ndim, a0.shape

(0, ())

In [18]:
# 1-d array
a1 = np.array([1,2])
a1.ndim, a1.shape

(1, (2,))

In [19]:
# 2-d array
a2 = np.array(([1,2], [3,4]))
a2.ndim, a2.shape

(2, (2, 2))

In [20]:
a = np.arange(10)

In [21]:
a.dtype

dtype('int64')

*** Array creation ***

In [23]:
a = np.array([1,2])
a

array([1, 2])

In [24]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [25]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [26]:
a = np.empty((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [28]:
a = np.eye(3,4,1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
a = np.diag(np.arange(4))
a

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [33]:
a = np.linspace(1,10,5) 
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

*** Specifying Types ***

In [36]:
a = np.arange(10, dtype=float)
a.dtype

dtype('float64')

In [38]:
a = np.arange(10, dtype=np.byte)
a.dtype

dtype('int8')

In [59]:
### Super important point here!
a[0] = 1000
a[0]
a[0].dtype


dtype('int8')

In [41]:
a1 = a.astype(np.int16)
a1[0] = 128
a1[0]

128

*** Reshaping and Concatenation ***

In [60]:
a = np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [61]:
# map a 0..63 1d array to a 8x8 2d array
a1 = a.reshape(8,8)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [62]:
a.shape = (8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [63]:
a.T

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

**** Stacking and concat ****

In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print (a.shape, b.shape)

(2, 2) (1, 2)


In [67]:
x = np.concatenate((a, b), axis=0) # vertical stack
print (x, x.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [68]:
y = np.concatenate((a, b.T), axis=1) # horizontal
print (y, y.shape)

[[1 2 5]
 [3 4 6]] (2, 3)


In [70]:
print (np.vstack((a,b)))
print (np.hstack((a,b.T)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [71]:
print (np.append(a, b, axis=0))
print (np.append(a, b.T, axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [77]:
print (np.insert(a, 0, b, axis=0))
print (np.insert(a, 0, b, axis=1))

[[5 1 2]
 [6 3 4]]


### Indexing/Slicing

In [78]:
a3 = np.arange(30) 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
print (a3[0])
print (a3[::-1])
print (a3[2:5])

0
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]
[2 3 4]


In [82]:
print (a3[[2,3,4,6,5,2]])

[2 3 4 6 5 2]


In [83]:
np.mod(a3, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2])

In [84]:
# list comprehension
[i for i in a3 if i % 3 == 0]

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [85]:
np.mod(a3, 3) == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False])

In [86]:
divisible_by_3 = np.mod(a3, 3) == 0
a3[divisible_by_3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [88]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [89]:
a[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [90]:
a[:,0]

array([ 0,  8, 16, 24, 32, 40, 48, 56])

In [91]:
a[:2,:2]

array([[0, 1],
       [8, 9]])

In [92]:
a[::2,::2]

array([[ 0,  2,  4,  6],
       [16, 18, 20, 22],
       [32, 34, 36, 38],
       [48, 50, 52, 54]])

In [94]:
b = np.arange(27).reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
b[0,:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
b[:,0,:]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [97]:
b[:,:,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

## Numpy Functions ##

In [99]:
import random
a = np.array([random.randint(0, 10) for i in range(10)])

print (a)
print (a.min())
print (a.max())
print (a.mean())
print (a.std()) # standard deviation
print (a.sum())

[8 6 4 9 8 9 0 1 9 4]
0
9
5.8
3.2186953878862163
58


In [101]:
b = np.arange(16).reshape(4, 4)
print (b)
print (b.T)
print (b.trace())
print (b.min())
print (b.min(axis=0))
print (b.min(axis=1))
print (b.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
30
0
[0 1 2 3]
[ 0  4  8 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [102]:
a = np.arange(0,3)
b = np.arange(1,4)
print (a, b)
print (np.dot(a,b))

[0 1 2] [1 2 3]
8


In [103]:
##Matrices
a = np.matrix([[3, 2, -1], [2, -2, 4], [-1, .5, -1]])
print (a)
print (a.trace())
print (a.diagonal())
print (a.T) # matrix transpose
print (a.I) # matrix inverse
print (a.H) # matrix conjugate transpose

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
[[0.]]
[[ 3. -2. -1.]]
[[ 3.   2.  -1. ]
 [ 2.  -2.   0.5]
 [-1.   4.  -1. ]]
[[ 1.48029737e-16 -5.00000000e-01 -2.00000000e+00]
 [ 6.66666667e-01  1.33333333e+00  4.66666667e+00]
 [ 3.33333333e-01  1.16666667e+00  3.33333333e+00]]
[[ 3.   2.  -1. ]
 [ 2.  -2.   0.5]
 [-1.   4.  -1. ]]


In [106]:
a = np.matrix(np.arange(0,6).reshape(2,3))
print (a * a) #it's ok to have an error, we need to use the transpose matrix!

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
a = matrix(arange(0,6).reshape(2,3))
print (a * a) #it's ok to have an error, we need to use the transpose matrix!

In [107]:
print (a * a.T)

[[ 5 14]
 [14 50]]
